inital Tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,13 +3,13 @@
 
 git add .
 
-# # Run dotnet build and test before commit
-# echo "Building"
-# cd FileProcessorApp
-# if ! dotnet build; then
-#   echo "Build failed. Commit aborted."
-#   exit 1
-# fi
+# Run dotnet build and test before commit
+echo "Building QuickBite API"
+cd src/QuickBite.API
+if ! dotnet build; then
+  echo "Build failed. Commit aborted."
+  exit 1
+fi
 
 # echo "checking format"
 # if ! dotnet format --verify-no-changes; then
@@ -17,24 +17,12 @@ git add .
 #   exit 1
 # fi
 
-# echo "Running Lib Project"
-# cd ../FileProcessorLib
-# if ! dotnet build; then
-#   echo "Lib Project build failed. Commit aborted."
-#   exit 1
-# fi
-# echo "checking format"
-# if ! dotnet format --verify-no-changes; then
-#   echo "Code format issues found. Please run 'dotnet format' to fix them. Commit aborted."
-#   exit 1
-# fi
-
-# echo "Running Tests"
-# cd ../FileProcessorTests
-# if ! dotnet test; then
-#   echo "Tests failed. Commit aborted."
-#   exit 1
-# fi
+echo "Running Tests"
+cd ../../tests/QuickBite.API.Tests
+if ! dotnet test; then
+  echo "Tests failed. Commit aborted."
+  exit 1
+fi
 
 # echo "checking format"
 # if ! dotnet format --verify-no-changes; then
